version: "3"

services:
  chowdown:
    image: jekyll/jekyll:3.8
    restart: always
    container_name: chowdown
    command: jekyll serve --force_polling --incremental
    ports:
      - "8080:4000"
    volumes:
      - .:/srv/jekyll
      - ./_components:/srv/jekyll/_components
      - ./_images:/srv/jekyll/_images
      - ./_posts:/srv/jekyll/_posts
      - ./_recipes:/srv/jekyll/_recipes
